# Generated by Django 4.2 on 2023-05-02 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_proyectos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(default='blank.jpg', upload_to='Proyectos/portadas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='video',
            field=models.FileField(null=True, upload_to='Proyectos/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
