# Generated by Django 4.2 on 2023-05-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_proyectos_imagen_alter_proyectos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='video',
            field=models.FileField(null=True, upload_to='Proyectos/videos'),
        ),
    ]
