# Generated by Django 4.2 on 2023-05-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_proyectos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='Logo')),
            ],
        ),
    ]
