# Generated by Django 4.2 on 2023-05-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='imagen_profesional',
            field=models.ImageField(default='blank.png', upload_to='Perfil'),
            preserve_default=False,
        ),
    ]
