# Generated by Django 4.2 on 2023-05-02 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_profesional_imagen_profesional'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
