# Generated by Django 4.2 on 2023-05-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_profesional_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='sobre_mi',
            field=models.TextField(default='N/a'),
        ),
    ]
