# Generated by Django 4.2 on 2023-05-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_profesional_sobre_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='cv',
            field=models.FileField(null=True, upload_to='Cv'),
        ),
    ]
