# Generated by Django 4.2 on 2023-05-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_profesional_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='link_github',
            field=models.CharField(default='w', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesional',
            name='link_linkedin',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
