# Generated by Django 4.2 on 2023-05-02 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_profesional_link_github_profesional_link_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descripción', models.TextField(default='N/a')),
                ('link', models.TextField(default='N/a')),
            ],
        ),
    ]
