# Generated by Django 4.2 on 2023-05-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_experiencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='fecha_duracion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
