# Generated by Django 4.2 on 2023-05-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_experiencia_fecha_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='aptitudes',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
